// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQusS8Xw4hQxZi9eED-Uj3Cd6FsLf-TPM',
    appId: '1:577116573557:web:0ec718198669cb73a24d3c',
    messagingSenderId: '577116573557',
    projectId: 'login-gg-2023',
    authDomain: 'login-gg-2023.firebaseapp.com',
    storageBucket: 'login-gg-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUsaUMA6whjPJqEeJjzlZtP7zoLNkQEqI',
    appId: '1:577116573557:android:4ea0a322fcd1e9bea24d3c',
    messagingSenderId: '577116573557',
    projectId: 'login-gg-2023',
    storageBucket: 'login-gg-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBXSznggekqWlOeGqohb_djwviKJLXsG0',
    appId: '1:577116573557:ios:170e8b80a52d743aa24d3c',
    messagingSenderId: '577116573557',
    projectId: 'login-gg-2023',
    storageBucket: 'login-gg-2023.appspot.com',
    iosClientId: '577116573557-5elj43p2q2u98j2fim1lbscqo356ii4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.project',
  );
}
